SELECT * FROM t FOR READ ONLY;
SELECT * FROM t 
  FOR UPDATE OF t2, t3 NOWAIT
  FOR KEY SHARE OF t4;
SELECT * FROM t LIMIT 5 FOR SHARE SKIP LOCKED;
SELECT * FROM t FOR NO KEY UPDATE LIMIT 10;

SELECT * FROM (SELECT * FROM mytable FOR UPDATE) ss WHERE col1 = 5;